services:

  navi_postgres-db:
    image: postgres:16
    container_name: navi_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: navi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - navi_postgres-data:/var/lib/postgresql/data

# TODO: software w/ free API key and its Docker image?
# See AI_SUMMARY... + Summary.md for more stuff
#  navi_python-ai:
#    image:
#    restart: always
#    ports:
#      - "5001:5001"
#    environment:
#      LLM_API_KEY:
#    depends_on:
#      - "postgres-db"

volumes:
  navi_postgres-data: